import { expect, test } from '@playwright/test';
const slug = 'auto-chords-regression';
const prefix = `bhajan-song-composer:compose:${slug}:`;
const source = 'X:1\nT:Auto chords regression\nM:4/4\nL:1/4\nK:C\n"G7"G A B c | C E G E |\nz C2 E | C4 |';

test('checkboxes automatically project chords, weighted dots, ABC and TimeGrid without processing buttons', async ({ page }) => {
  await page.addInitScript(({ key, abc }) => localStorage.setItem(key, abc), { key: prefix + 'melody', abc: source });
  await page.goto(`/compose/${slug}/harmony`);
  const left = page.getByRole('complementary', { name: 'Score tools' });
  const right = page.getByRole('complementary', { name: 'Harmony assistant' });
  await expect(left.getByRole('checkbox', { name: 'Missing Chord', exact: true })).toBeEnabled();
  await expect(page.getByRole('button', { name: 'Fill missing chords', exact: true })).toHaveCount(0);
  await expect(page.locator('summary').filter({ hasText: 'Detected strong beats' })).toHaveCount(0);
  await expect(left.locator('summary')).toHaveCount(1);
  await right.locator('summary').filter({ hasText: 'ABC notation' }).click();
  await right.locator('summary').filter({ hasText: 'TimeGrid JSON' }).click();
  const playbackAbc = right.getByLabel('Harmony playback ABC');
  const grid = right.getByLabel('Harmony TimeGrid JSON');
  const score = page.locator('#composer-harmony-preview');
  const countChords = async () => ((await playbackAbc.textContent())?.match(/"[A-G][^"]*"/g) ?? []).length;
  const initial = await playbackAbc.textContent();
  await expect.poll(countChords).toBe(1);
  await left.getByRole('checkbox', { name: 'Strong Beats', exact: true }).check();
  await expect(playbackAbc).toContainText('w: ⬤ • ● •');
  await expect(score).toContainText('⬤');
  await expect(score).toContainText('●');
  await expect(score.locator('.beat-strong').first()).toBeVisible();
  await expect(score.locator('.beat-medium').first()).toBeVisible();
  await expect(score.locator('.beat-soft').first()).toBeVisible();
  const sizes = await Promise.all(['.beat-strong', '.beat-medium', '.beat-soft'].map(selector => score.locator(selector).first().evaluate(el => parseFloat(getComputedStyle(el).fontSize))));
  expect(sizes[0]).toBeGreaterThan(sizes[1]);
  expect(sizes[1]).toBeGreaterThan(sizes[2]);
  for (const selector of ['.beat-strong', '.beat-medium', '.beat-soft']) await expect(score.locator(selector).first()).toHaveCSS('fill', 'rgb(0, 0, 0)');
  await page.screenshot({ path: '/tmp/harmony-automatic-layers.png', fullPage: true });
  await expect(grid).toContainText('"weight": "⬤"');
  await left.getByRole('checkbox', { name: 'Missing Chord', exact: true }).check();
  await expect.poll(countChords).toBe(4);
  await expect(score.locator('[data-guitar-chord]').first()).toBeVisible();
  await expect(playbackAbc).not.toContainText('Missing chord');
  await left.getByRole('checkbox', { name: 'Strong Beats', exact: true }).uncheck();
  await expect(playbackAbc).not.toContainText('⬤');
  await expect(score).not.toContainText('⬤');
  await expect.poll(countChords).toBe(4);
  await left.getByRole('checkbox', { name: 'Missing Chord', exact: true }).uncheck();
  await expect.poll(countChords).toBe(1);
  await expect(playbackAbc).toHaveText(initial!);
  expect(await page.evaluate(key => localStorage.getItem(key), prefix + 'melody')).toBe(source);
  expect(await page.evaluate(key => localStorage.getItem(key), prefix + 'manual-harmony-draft')).toBeNull();
});
